jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Replace API Key
      run: |
        # Заменяем заглушку на секрет прямо в корневом файле
        sed -i 's|__GOOGLE_CALENDAR_API_KEY__|'"${{ secrets.GOOGLE_CALENDAR_API_KEY }}"'|g' ./index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Указываем текущую директорию (корень) для публикации
        publish_dir: ./
