jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Build and Replace
      run: |
        # Эта команда найдет index.html и в корне, и в папке public (если она есть)
        find . -name "index.html" -exec sed -i 's|__GOOGLE_CALENDAR_API_KEY__|'"${{ secrets.GOOGLE_CALENDAR_API_KEY }}"'|g' {} +

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # Или укажите ./public, если вы используете генератор сайта
